name: adhd_tracker
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  awesome_notifications: ^0.8.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  file_picker: ^8.3.5
  fl_chart: ^0.69.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  material_design_icons_flutter: ^7.0.7296
  path_provider: ^2.1.2
  provider: ^6.1.1
  share_plus: ^10.1.3
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  table_calendar: ^3.1.3
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.1


dependency_overrides:
  webview_flutter_wkwebview: 3.17.0
  
dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/default.png
    - assets/images/demo1.png

  fonts:
    - family: Nordique
      fonts:
        - asset: assets/fonts/font2.ttf
    - family: Yaro
      fonts:
        - asset: assets/fonts/font3.ttf
